import "dotenv/config";

const {
  MONGO_URI,
  JWT_SECRET,
  SENDGRID_API_KEY,
  BASE_URL,
  SENDGRID_TEMPLATE_ID_VERIFY,
  FROM_EMAIL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
} = process.env;

if (
  !MONGO_URI ||
  !JWT_SECRET ||
  !SENDGRID_API_KEY ||
  !BASE_URL ||
  !SENDGRID_TEMPLATE_ID_VERIFY ||
  !FROM_EMAIL ||
  !CLOUDINARY_CLOUD_NAME ||
  !CLOUDINARY_API_KEY ||
  !CLOUDINARY_API_SECRET
) {
  throw new Error("ENV is missing!");
}

export {
  MONGO_URI,
  JWT_SECRET,
  SENDGRID_API_KEY,
  BASE_URL,
  SENDGRID_TEMPLATE_ID_VERIFY,
  FROM_EMAIL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
};
